
- name: Импорт APT ключей Grafana-ы
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present
  tags: grafana

- name: Добавляю репозиторий Grafana-ы в систему
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
  tags: grafana

- name: Установка Grafana-ы и запуск её в Deamon режиме
  apt:
    name: grafana
    state: present
  notify:
    - grafana systemd
  tags: grafana
